// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: saasyd_usability_business_task_grpc.proto

package usability_business_task_c

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Code int32

const (
	Code_SUCCESS        Code = 0
	Code_REQUEST_FAILED Code = 500
	Code_PARAM_ERROR    Code = 501
	Code_FAIL           Code = 1
)

// Enum value maps for Code.
var (
	Code_name = map[int32]string{
		0:   "SUCCESS",
		500: "REQUEST_FAILED",
		501: "PARAM_ERROR",
		1:   "FAIL",
	}
	Code_value = map[string]int32{
		"SUCCESS":        0,
		"REQUEST_FAILED": 500,
		"PARAM_ERROR":    501,
		"FAIL":           1,
	}
)

func (x Code) Enum() *Code {
	p := new(Code)
	*p = x
	return p
}

func (x Code) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Code) Descriptor() protoreflect.EnumDescriptor {
	return file_saasyd_usability_business_task_grpc_proto_enumTypes[0].Descriptor()
}

func (Code) Type() protoreflect.EnumType {
	return &file_saasyd_usability_business_task_grpc_proto_enumTypes[0]
}

func (x Code) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Code.Descriptor instead.
func (Code) EnumDescriptor() ([]byte, []int) {
	return file_saasyd_usability_business_task_grpc_proto_rawDescGZIP(), []int{0}
}

type BusinessTaskReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Offset int32 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit  int32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *BusinessTaskReq) Reset() {
	*x = BusinessTaskReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_saasyd_usability_business_task_grpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BusinessTaskReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BusinessTaskReq) ProtoMessage() {}

func (x *BusinessTaskReq) ProtoReflect() protoreflect.Message {
	mi := &file_saasyd_usability_business_task_grpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BusinessTaskReq.ProtoReflect.Descriptor instead.
func (*BusinessTaskReq) Descriptor() ([]byte, []int) {
	return file_saasyd_usability_business_task_grpc_proto_rawDescGZIP(), []int{0}
}

func (x *BusinessTaskReq) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *BusinessTaskReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type BusinessTaskRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    Code                  `protobuf:"varint,1,opt,name=code,proto3,enum=usability_business_task_c.Code" json:"code,omitempty"`
	Message string                `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data    *BusinessTaskRsp_Data `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *BusinessTaskRsp) Reset() {
	*x = BusinessTaskRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_saasyd_usability_business_task_grpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BusinessTaskRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BusinessTaskRsp) ProtoMessage() {}

func (x *BusinessTaskRsp) ProtoReflect() protoreflect.Message {
	mi := &file_saasyd_usability_business_task_grpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BusinessTaskRsp.ProtoReflect.Descriptor instead.
func (*BusinessTaskRsp) Descriptor() ([]byte, []int) {
	return file_saasyd_usability_business_task_grpc_proto_rawDescGZIP(), []int{1}
}

func (x *BusinessTaskRsp) GetCode() Code {
	if x != nil {
		return x.Code
	}
	return Code_SUCCESS
}

func (x *BusinessTaskRsp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BusinessTaskRsp) GetData() *BusinessTaskRsp_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type BusinessTaskRsp_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskList []*BusinessTaskRsp_Data_BusinessTask `protobuf:"bytes,1,rep,name=TaskList,proto3" json:"TaskList,omitempty"`
	Total    int32                                `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *BusinessTaskRsp_Data) Reset() {
	*x = BusinessTaskRsp_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_saasyd_usability_business_task_grpc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BusinessTaskRsp_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BusinessTaskRsp_Data) ProtoMessage() {}

func (x *BusinessTaskRsp_Data) ProtoReflect() protoreflect.Message {
	mi := &file_saasyd_usability_business_task_grpc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BusinessTaskRsp_Data.ProtoReflect.Descriptor instead.
func (*BusinessTaskRsp_Data) Descriptor() ([]byte, []int) {
	return file_saasyd_usability_business_task_grpc_proto_rawDescGZIP(), []int{1, 0}
}

func (x *BusinessTaskRsp_Data) GetTaskList() []*BusinessTaskRsp_Data_BusinessTask {
	if x != nil {
		return x.TaskList
	}
	return nil
}

func (x *BusinessTaskRsp_Data) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type BusinessTaskRsp_Data_BusinessTask struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url       string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Frequency int32  `protobuf:"varint,4,opt,name=frequency,proto3" json:"frequency,omitempty"`
}

func (x *BusinessTaskRsp_Data_BusinessTask) Reset() {
	*x = BusinessTaskRsp_Data_BusinessTask{}
	if protoimpl.UnsafeEnabled {
		mi := &file_saasyd_usability_business_task_grpc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BusinessTaskRsp_Data_BusinessTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BusinessTaskRsp_Data_BusinessTask) ProtoMessage() {}

func (x *BusinessTaskRsp_Data_BusinessTask) ProtoReflect() protoreflect.Message {
	mi := &file_saasyd_usability_business_task_grpc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BusinessTaskRsp_Data_BusinessTask.ProtoReflect.Descriptor instead.
func (*BusinessTaskRsp_Data_BusinessTask) Descriptor() ([]byte, []int) {
	return file_saasyd_usability_business_task_grpc_proto_rawDescGZIP(), []int{1, 0, 0}
}

func (x *BusinessTaskRsp_Data_BusinessTask) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *BusinessTaskRsp_Data_BusinessTask) GetFrequency() int32 {
	if x != nil {
		return x.Frequency
	}
	return 0
}

var File_saasyd_usability_business_task_grpc_proto protoreflect.FileDescriptor

var file_saasyd_usability_business_task_grpc_proto_rawDesc = []byte{
	0x0a, 0x29, 0x73, 0x61, 0x61, 0x73, 0x79, 0x64, 0x5f, 0x75, 0x73, 0x61, 0x62, 0x69, 0x6c, 0x69,
	0x74, 0x79, 0x5f, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x5f, 0x74, 0x61, 0x73, 0x6b,
	0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x19, 0x75, 0x73, 0x61,
	0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x5f, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x5f,
	0x74, 0x61, 0x73, 0x6b, 0x5f, 0x63, 0x22, 0x3f, 0x0a, 0x0f, 0x42, 0x75, 0x73, 0x69, 0x6e, 0x65,
	0x73, 0x73, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66,
	0x73, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0xde, 0x02, 0x0a, 0x0f, 0x42, 0x75, 0x73, 0x69,
	0x6e, 0x65, 0x73, 0x73, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x73, 0x70, 0x12, 0x33, 0x0a, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1f, 0x2e, 0x75, 0x73, 0x61, 0x62,
	0x69, 0x6c, 0x69, 0x74, 0x79, 0x5f, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x5f, 0x74,
	0x61, 0x73, 0x6b, 0x5f, 0x63, 0x2e, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x43, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x75, 0x73, 0x61, 0x62, 0x69,
	0x6c, 0x69, 0x74, 0x79, 0x5f, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x5f, 0x74, 0x61,
	0x73, 0x6b, 0x5f, 0x63, 0x2e, 0x42, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x54, 0x61, 0x73,
	0x6b, 0x52, 0x73, 0x70, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a,
	0xb6, 0x01, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x58, 0x0a, 0x08, 0x54, 0x61, 0x73, 0x6b,
	0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x3c, 0x2e, 0x75, 0x73, 0x61,
	0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x5f, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x5f,
	0x74, 0x61, 0x73, 0x6b, 0x5f, 0x63, 0x2e, 0x42, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x54,
	0x61, 0x73, 0x6b, 0x52, 0x73, 0x70, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x42, 0x75, 0x73, 0x69,
	0x6e, 0x65, 0x73, 0x73, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x08, 0x54, 0x61, 0x73, 0x6b, 0x4c, 0x69,
	0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x1a, 0x3e, 0x0a, 0x0c, 0x42, 0x75, 0x73, 0x69,
	0x6e, 0x65, 0x73, 0x73, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x1c, 0x0a, 0x09, 0x66, 0x72,
	0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x66,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x79, 0x2a, 0x44, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65,
	0x12, 0x0b, 0x0a, 0x07, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x00, 0x12, 0x13, 0x0a,
	0x0e, 0x52, 0x45, 0x51, 0x55, 0x45, 0x53, 0x54, 0x5f, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10,
	0xf4, 0x03, 0x12, 0x10, 0x0a, 0x0b, 0x50, 0x41, 0x52, 0x41, 0x4d, 0x5f, 0x45, 0x52, 0x52, 0x4f,
	0x52, 0x10, 0xf5, 0x03, 0x12, 0x08, 0x0a, 0x04, 0x46, 0x41, 0x49, 0x4c, 0x10, 0x01, 0x32, 0x7f,
	0x0a, 0x10, 0x42, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x54, 0x61, 0x73, 0x6b, 0x4c, 0x69,
	0x73, 0x74, 0x12, 0x6b, 0x0a, 0x0f, 0x67, 0x65, 0x74, 0x42, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73,
	0x73, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x2a, 0x2e, 0x75, 0x73, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74,
	0x79, 0x5f, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x5f, 0x74, 0x61, 0x73, 0x6b, 0x5f,
	0x63, 0x2e, 0x42, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65,
	0x71, 0x1a, 0x2a, 0x2e, 0x75, 0x73, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x5f, 0x62, 0x75,
	0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x5f, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x63, 0x2e, 0x42, 0x75,
	0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x73, 0x70, 0x22, 0x00, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_saasyd_usability_business_task_grpc_proto_rawDescOnce sync.Once
	file_saasyd_usability_business_task_grpc_proto_rawDescData = file_saasyd_usability_business_task_grpc_proto_rawDesc
)

func file_saasyd_usability_business_task_grpc_proto_rawDescGZIP() []byte {
	file_saasyd_usability_business_task_grpc_proto_rawDescOnce.Do(func() {
		file_saasyd_usability_business_task_grpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_saasyd_usability_business_task_grpc_proto_rawDescData)
	})
	return file_saasyd_usability_business_task_grpc_proto_rawDescData
}

var file_saasyd_usability_business_task_grpc_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_saasyd_usability_business_task_grpc_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_saasyd_usability_business_task_grpc_proto_goTypes = []interface{}{
	(Code)(0),                                 // 0: usability_business_task_c.Code
	(*BusinessTaskReq)(nil),                   // 1: usability_business_task_c.BusinessTaskReq
	(*BusinessTaskRsp)(nil),                   // 2: usability_business_task_c.BusinessTaskRsp
	(*BusinessTaskRsp_Data)(nil),              // 3: usability_business_task_c.BusinessTaskRsp.Data
	(*BusinessTaskRsp_Data_BusinessTask)(nil), // 4: usability_business_task_c.BusinessTaskRsp.Data.BusinessTask
}
var file_saasyd_usability_business_task_grpc_proto_depIdxs = []int32{
	0, // 0: usability_business_task_c.BusinessTaskRsp.code:type_name -> usability_business_task_c.Code
	3, // 1: usability_business_task_c.BusinessTaskRsp.data:type_name -> usability_business_task_c.BusinessTaskRsp.Data
	4, // 2: usability_business_task_c.BusinessTaskRsp.Data.TaskList:type_name -> usability_business_task_c.BusinessTaskRsp.Data.BusinessTask
	1, // 3: usability_business_task_c.BusinessTaskList.getBusinessTask:input_type -> usability_business_task_c.BusinessTaskReq
	2, // 4: usability_business_task_c.BusinessTaskList.getBusinessTask:output_type -> usability_business_task_c.BusinessTaskRsp
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_saasyd_usability_business_task_grpc_proto_init() }
func file_saasyd_usability_business_task_grpc_proto_init() {
	if File_saasyd_usability_business_task_grpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_saasyd_usability_business_task_grpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BusinessTaskReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_saasyd_usability_business_task_grpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BusinessTaskRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_saasyd_usability_business_task_grpc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BusinessTaskRsp_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_saasyd_usability_business_task_grpc_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BusinessTaskRsp_Data_BusinessTask); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_saasyd_usability_business_task_grpc_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_saasyd_usability_business_task_grpc_proto_goTypes,
		DependencyIndexes: file_saasyd_usability_business_task_grpc_proto_depIdxs,
		EnumInfos:         file_saasyd_usability_business_task_grpc_proto_enumTypes,
		MessageInfos:      file_saasyd_usability_business_task_grpc_proto_msgTypes,
	}.Build()
	File_saasyd_usability_business_task_grpc_proto = out.File
	file_saasyd_usability_business_task_grpc_proto_rawDesc = nil
	file_saasyd_usability_business_task_grpc_proto_goTypes = nil
	file_saasyd_usability_business_task_grpc_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// BusinessTaskListClient is the client API for BusinessTaskList service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BusinessTaskListClient interface {
	GetBusinessTask(ctx context.Context, in *BusinessTaskReq, opts ...grpc.CallOption) (*BusinessTaskRsp, error)
}

type businessTaskListClient struct {
	cc grpc.ClientConnInterface
}

func NewBusinessTaskListClient(cc grpc.ClientConnInterface) BusinessTaskListClient {
	return &businessTaskListClient{cc}
}

func (c *businessTaskListClient) GetBusinessTask(ctx context.Context, in *BusinessTaskReq, opts ...grpc.CallOption) (*BusinessTaskRsp, error) {
	out := new(BusinessTaskRsp)
	err := c.cc.Invoke(ctx, "/usability_business_task_c.BusinessTaskList/getBusinessTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BusinessTaskListServer is the server API for BusinessTaskList service.
type BusinessTaskListServer interface {
	GetBusinessTask(context.Context, *BusinessTaskReq) (*BusinessTaskRsp, error)
}

// UnimplementedBusinessTaskListServer can be embedded to have forward compatible implementations.
type UnimplementedBusinessTaskListServer struct {
}

func (*UnimplementedBusinessTaskListServer) GetBusinessTask(context.Context, *BusinessTaskReq) (*BusinessTaskRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBusinessTask not implemented")
}

func RegisterBusinessTaskListServer(s *grpc.Server, srv BusinessTaskListServer) {
	s.RegisterService(&_BusinessTaskList_serviceDesc, srv)
}

func _BusinessTaskList_GetBusinessTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BusinessTaskReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessTaskListServer).GetBusinessTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/usability_business_task_c.BusinessTaskList/GetBusinessTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessTaskListServer).GetBusinessTask(ctx, req.(*BusinessTaskReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _BusinessTaskList_serviceDesc = grpc.ServiceDesc{
	ServiceName: "usability_business_task_c.BusinessTaskList",
	HandlerType: (*BusinessTaskListServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getBusinessTask",
			Handler:    _BusinessTaskList_GetBusinessTask_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "saasyd_usability_business_task_grpc.proto",
}
