// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb_mdbg.proto

package sspb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PBMDbgReq struct {
	Cmdname              string   `protobuf:"bytes,1,opt,name=cmdname,proto3" json:"cmdname,omitempty"`
	Cmdreq               string   `protobuf:"bytes,2,opt,name=cmdreq,proto3" json:"cmdreq,omitempty"`
	Uname                string   `protobuf:"bytes,3,opt,name=uname,proto3" json:"uname,omitempty"`
	Uid                  int32    `protobuf:"varint,4,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PBMDbgReq) Reset()         { *m = PBMDbgReq{} }
func (m *PBMDbgReq) String() string { return proto.CompactTextString(m) }
func (*PBMDbgReq) ProtoMessage()    {}
func (*PBMDbgReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2bb6c15db10c994, []int{0}
}

func (m *PBMDbgReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PBMDbgReq.Unmarshal(m, b)
}
func (m *PBMDbgReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PBMDbgReq.Marshal(b, m, deterministic)
}
func (m *PBMDbgReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PBMDbgReq.Merge(m, src)
}
func (m *PBMDbgReq) XXX_Size() int {
	return xxx_messageInfo_PBMDbgReq.Size(m)
}
func (m *PBMDbgReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PBMDbgReq.DiscardUnknown(m)
}

var xxx_messageInfo_PBMDbgReq proto.InternalMessageInfo

func (m *PBMDbgReq) GetCmdname() string {
	if m != nil {
		return m.Cmdname
	}
	return ""
}

func (m *PBMDbgReq) GetCmdreq() string {
	if m != nil {
		return m.Cmdreq
	}
	return ""
}

func (m *PBMDbgReq) GetUname() string {
	if m != nil {
		return m.Uname
	}
	return ""
}

func (m *PBMDbgReq) GetUid() int32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

type PBMDbgRsp struct {
	Result               int32    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Cmdrsp               []byte   `protobuf:"bytes,3,opt,name=cmdrsp,proto3" json:"cmdrsp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PBMDbgRsp) Reset()         { *m = PBMDbgRsp{} }
func (m *PBMDbgRsp) String() string { return proto.CompactTextString(m) }
func (*PBMDbgRsp) ProtoMessage()    {}
func (*PBMDbgRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2bb6c15db10c994, []int{1}
}

func (m *PBMDbgRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PBMDbgRsp.Unmarshal(m, b)
}
func (m *PBMDbgRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PBMDbgRsp.Marshal(b, m, deterministic)
}
func (m *PBMDbgRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PBMDbgRsp.Merge(m, src)
}
func (m *PBMDbgRsp) XXX_Size() int {
	return xxx_messageInfo_PBMDbgRsp.Size(m)
}
func (m *PBMDbgRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_PBMDbgRsp.DiscardUnknown(m)
}

var xxx_messageInfo_PBMDbgRsp proto.InternalMessageInfo

func (m *PBMDbgRsp) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func (m *PBMDbgRsp) GetCmdrsp() []byte {
	if m != nil {
		return m.Cmdrsp
	}
	return nil
}

type PBMDbgHelp struct {
	Cmdname              string   `protobuf:"bytes,1,opt,name=cmdname,proto3" json:"cmdname,omitempty"`
	Cmdhelp              string   `protobuf:"bytes,2,opt,name=cmdhelp,proto3" json:"cmdhelp,omitempty"`
	Limit                string   `protobuf:"bytes,3,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PBMDbgHelp) Reset()         { *m = PBMDbgHelp{} }
func (m *PBMDbgHelp) String() string { return proto.CompactTextString(m) }
func (*PBMDbgHelp) ProtoMessage()    {}
func (*PBMDbgHelp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2bb6c15db10c994, []int{2}
}

func (m *PBMDbgHelp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PBMDbgHelp.Unmarshal(m, b)
}
func (m *PBMDbgHelp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PBMDbgHelp.Marshal(b, m, deterministic)
}
func (m *PBMDbgHelp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PBMDbgHelp.Merge(m, src)
}
func (m *PBMDbgHelp) XXX_Size() int {
	return xxx_messageInfo_PBMDbgHelp.Size(m)
}
func (m *PBMDbgHelp) XXX_DiscardUnknown() {
	xxx_messageInfo_PBMDbgHelp.DiscardUnknown(m)
}

var xxx_messageInfo_PBMDbgHelp proto.InternalMessageInfo

func (m *PBMDbgHelp) GetCmdname() string {
	if m != nil {
		return m.Cmdname
	}
	return ""
}

func (m *PBMDbgHelp) GetCmdhelp() string {
	if m != nil {
		return m.Cmdhelp
	}
	return ""
}

func (m *PBMDbgHelp) GetLimit() string {
	if m != nil {
		return m.Limit
	}
	return ""
}

type PBMDbgHelpRsp struct {
	Commands             []*PBMDbgHelp `protobuf:"bytes,1,rep,name=commands,proto3" json:"commands,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *PBMDbgHelpRsp) Reset()         { *m = PBMDbgHelpRsp{} }
func (m *PBMDbgHelpRsp) String() string { return proto.CompactTextString(m) }
func (*PBMDbgHelpRsp) ProtoMessage()    {}
func (*PBMDbgHelpRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2bb6c15db10c994, []int{3}
}

func (m *PBMDbgHelpRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PBMDbgHelpRsp.Unmarshal(m, b)
}
func (m *PBMDbgHelpRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PBMDbgHelpRsp.Marshal(b, m, deterministic)
}
func (m *PBMDbgHelpRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PBMDbgHelpRsp.Merge(m, src)
}
func (m *PBMDbgHelpRsp) XXX_Size() int {
	return xxx_messageInfo_PBMDbgHelpRsp.Size(m)
}
func (m *PBMDbgHelpRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_PBMDbgHelpRsp.DiscardUnknown(m)
}

var xxx_messageInfo_PBMDbgHelpRsp proto.InternalMessageInfo

func (m *PBMDbgHelpRsp) GetCommands() []*PBMDbgHelp {
	if m != nil {
		return m.Commands
	}
	return nil
}

func init() {
	proto.RegisterType((*PBMDbgReq)(nil), "sspb.PBMDbgReq")
	proto.RegisterType((*PBMDbgRsp)(nil), "sspb.PBMDbgRsp")
	proto.RegisterType((*PBMDbgHelp)(nil), "sspb.PBMDbgHelp")
	proto.RegisterType((*PBMDbgHelpRsp)(nil), "sspb.PBMDbgHelpRsp")
}

func init() { proto.RegisterFile("pb_mdbg.proto", fileDescriptor_a2bb6c15db10c994) }

var fileDescriptor_a2bb6c15db10c994 = []byte{
	// 222 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0x3f, 0x4b, 0xc0, 0x30,
	0x10, 0xc5, 0x89, 0xfd, 0xa3, 0x3d, 0x2d, 0x94, 0x20, 0x92, 0xb1, 0x64, 0xea, 0x20, 0x1d, 0x74,
	0x14, 0x17, 0x71, 0x70, 0x11, 0x24, 0x83, 0xab, 0x34, 0x4d, 0xa8, 0x85, 0xa4, 0x4d, 0x9b, 0xf6,
	0xfb, 0x4b, 0xd2, 0xa4, 0x3a, 0xb9, 0xe5, 0x97, 0x7b, 0xf7, 0xde, 0xe3, 0xa0, 0x34, 0xfc, 0x4b,
	0x0b, 0x3e, 0xb4, 0x66, 0x9d, 0xb7, 0x19, 0xa7, 0xd6, 0x1a, 0x4e, 0x25, 0x14, 0x1f, 0x2f, 0xef,
	0xaf, 0x7c, 0x60, 0x72, 0xc1, 0x04, 0x2e, 0x7b, 0x2d, 0xa6, 0x4e, 0x4b, 0x82, 0x6a, 0xd4, 0x14,
	0x2c, 0x22, 0xbe, 0x83, 0xbc, 0xd7, 0x62, 0x95, 0x0b, 0xb9, 0xf0, 0x83, 0x40, 0xf8, 0x16, 0xb2,
	0xdd, 0xeb, 0x13, 0xff, 0x7d, 0x00, 0xae, 0x20, 0xd9, 0x47, 0x41, 0xd2, 0x1a, 0x35, 0x19, 0x73,
	0x4f, 0xfa, 0x74, 0xc6, 0x58, 0xe3, 0xcc, 0x56, 0x69, 0x77, 0xb5, 0xf9, 0x94, 0x8c, 0x05, 0x8a,
	0x21, 0xd6, 0x78, 0xb7, 0x1b, 0x16, 0x88, 0x7e, 0x02, 0x1c, 0xcb, 0x6f, 0x52, 0x99, 0x7f, 0x4a,
	0x1e, 0x93, 0x6f, 0xa9, 0x4c, 0x68, 0x19, 0xd1, 0xd5, 0x54, 0xa3, 0x1e, 0xb7, 0x58, 0xd3, 0x03,
	0x7d, 0x86, 0xf2, 0xd7, 0xd7, 0x15, 0xbb, 0x87, 0xab, 0x7e, 0xd6, 0xba, 0x9b, 0x84, 0x25, 0xa8,
	0x4e, 0x9a, 0xeb, 0x87, 0xaa, 0x75, 0x57, 0x6a, 0xff, 0xc8, 0x4e, 0x05, 0xcf, 0xfd, 0x1d, 0x1f,
	0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x28, 0xfe, 0xcc, 0xc9, 0x58, 0x01, 0x00, 0x00,
}
