// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb_stream.proto

package sspb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PBStreamOpen struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Src                  string   `protobuf:"bytes,2,opt,name=src,proto3" json:"src,omitempty"`
	Dst                  string   `protobuf:"bytes,3,opt,name=dst,proto3" json:"dst,omitempty"`
	LocalWin             int32    `protobuf:"varint,6,opt,name=localWin,proto3" json:"localWin,omitempty"`
	PeerWin              int32    `protobuf:"varint,7,opt,name=peerWin,proto3" json:"peerWin,omitempty"`
	Ext                  string   `protobuf:"bytes,11,opt,name=ext,proto3" json:"ext,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PBStreamOpen) Reset()         { *m = PBStreamOpen{} }
func (m *PBStreamOpen) String() string { return proto.CompactTextString(m) }
func (*PBStreamOpen) ProtoMessage()    {}
func (*PBStreamOpen) Descriptor() ([]byte, []int) {
	return fileDescriptor_e6b7e2749f16bac2, []int{0}
}

func (m *PBStreamOpen) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PBStreamOpen.Unmarshal(m, b)
}
func (m *PBStreamOpen) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PBStreamOpen.Marshal(b, m, deterministic)
}
func (m *PBStreamOpen) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PBStreamOpen.Merge(m, src)
}
func (m *PBStreamOpen) XXX_Size() int {
	return xxx_messageInfo_PBStreamOpen.Size(m)
}
func (m *PBStreamOpen) XXX_DiscardUnknown() {
	xxx_messageInfo_PBStreamOpen.DiscardUnknown(m)
}

var xxx_messageInfo_PBStreamOpen proto.InternalMessageInfo

func (m *PBStreamOpen) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PBStreamOpen) GetSrc() string {
	if m != nil {
		return m.Src
	}
	return ""
}

func (m *PBStreamOpen) GetDst() string {
	if m != nil {
		return m.Dst
	}
	return ""
}

func (m *PBStreamOpen) GetLocalWin() int32 {
	if m != nil {
		return m.LocalWin
	}
	return 0
}

func (m *PBStreamOpen) GetPeerWin() int32 {
	if m != nil {
		return m.PeerWin
	}
	return 0
}

func (m *PBStreamOpen) GetExt() string {
	if m != nil {
		return m.Ext
	}
	return ""
}

type PBStreamClose struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Reason               string   `protobuf:"bytes,6,opt,name=reason,proto3" json:"reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PBStreamClose) Reset()         { *m = PBStreamClose{} }
func (m *PBStreamClose) String() string { return proto.CompactTextString(m) }
func (*PBStreamClose) ProtoMessage()    {}
func (*PBStreamClose) Descriptor() ([]byte, []int) {
	return fileDescriptor_e6b7e2749f16bac2, []int{1}
}

func (m *PBStreamClose) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PBStreamClose.Unmarshal(m, b)
}
func (m *PBStreamClose) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PBStreamClose.Marshal(b, m, deterministic)
}
func (m *PBStreamClose) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PBStreamClose.Merge(m, src)
}
func (m *PBStreamClose) XXX_Size() int {
	return xxx_messageInfo_PBStreamClose.Size(m)
}
func (m *PBStreamClose) XXX_DiscardUnknown() {
	xxx_messageInfo_PBStreamClose.DiscardUnknown(m)
}

var xxx_messageInfo_PBStreamClose proto.InternalMessageInfo

func (m *PBStreamClose) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PBStreamClose) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

type PBStreamData struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Data                 []byte   `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PBStreamData) Reset()         { *m = PBStreamData{} }
func (m *PBStreamData) String() string { return proto.CompactTextString(m) }
func (*PBStreamData) ProtoMessage()    {}
func (*PBStreamData) Descriptor() ([]byte, []int) {
	return fileDescriptor_e6b7e2749f16bac2, []int{2}
}

func (m *PBStreamData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PBStreamData.Unmarshal(m, b)
}
func (m *PBStreamData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PBStreamData.Marshal(b, m, deterministic)
}
func (m *PBStreamData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PBStreamData.Merge(m, src)
}
func (m *PBStreamData) XXX_Size() int {
	return xxx_messageInfo_PBStreamData.Size(m)
}
func (m *PBStreamData) XXX_DiscardUnknown() {
	xxx_messageInfo_PBStreamData.DiscardUnknown(m)
}

var xxx_messageInfo_PBStreamData proto.InternalMessageInfo

func (m *PBStreamData) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PBStreamData) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type PBStreamUpdateWindow struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Win                  int32    `protobuf:"varint,5,opt,name=win,proto3" json:"win,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PBStreamUpdateWindow) Reset()         { *m = PBStreamUpdateWindow{} }
func (m *PBStreamUpdateWindow) String() string { return proto.CompactTextString(m) }
func (*PBStreamUpdateWindow) ProtoMessage()    {}
func (*PBStreamUpdateWindow) Descriptor() ([]byte, []int) {
	return fileDescriptor_e6b7e2749f16bac2, []int{3}
}

func (m *PBStreamUpdateWindow) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PBStreamUpdateWindow.Unmarshal(m, b)
}
func (m *PBStreamUpdateWindow) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PBStreamUpdateWindow.Marshal(b, m, deterministic)
}
func (m *PBStreamUpdateWindow) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PBStreamUpdateWindow.Merge(m, src)
}
func (m *PBStreamUpdateWindow) XXX_Size() int {
	return xxx_messageInfo_PBStreamUpdateWindow.Size(m)
}
func (m *PBStreamUpdateWindow) XXX_DiscardUnknown() {
	xxx_messageInfo_PBStreamUpdateWindow.DiscardUnknown(m)
}

var xxx_messageInfo_PBStreamUpdateWindow proto.InternalMessageInfo

func (m *PBStreamUpdateWindow) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PBStreamUpdateWindow) GetWin() int32 {
	if m != nil {
		return m.Win
	}
	return 0
}

func init() {
	proto.RegisterType((*PBStreamOpen)(nil), "sspb.PBStreamOpen")
	proto.RegisterType((*PBStreamClose)(nil), "sspb.PBStreamClose")
	proto.RegisterType((*PBStreamData)(nil), "sspb.PBStreamData")
	proto.RegisterType((*PBStreamUpdateWindow)(nil), "sspb.PBStreamUpdateWindow")
}

func init() { proto.RegisterFile("pb_stream.proto", fileDescriptor_e6b7e2749f16bac2) }

var fileDescriptor_e6b7e2749f16bac2 = []byte{
	// 232 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x50, 0x3d, 0x4f, 0xc3, 0x30,
	0x14, 0x94, 0xd3, 0x34, 0xa5, 0x8f, 0xf2, 0x21, 0x0b, 0x21, 0x8b, 0x29, 0xca, 0x94, 0x89, 0x01,
	0x06, 0x98, 0x81, 0x1d, 0x64, 0x84, 0x3a, 0x22, 0xa7, 0x7e, 0x83, 0xa5, 0x10, 0x5b, 0x7e, 0x4f,
	0x6a, 0x7f, 0x03, 0xbf, 0x1a, 0xd9, 0x21, 0x30, 0xa4, 0xdb, 0xdd, 0x3b, 0xdd, 0xf9, 0x7c, 0x70,
	0x11, 0xba, 0x4f, 0xe2, 0x88, 0xe6, 0xeb, 0x36, 0x44, 0xcf, 0x5e, 0x96, 0x44, 0xa1, 0x6b, 0xbe,
	0x05, 0x6c, 0xde, 0x9e, 0xde, 0xb3, 0xf0, 0x1a, 0x70, 0x90, 0xe7, 0x50, 0x38, 0xab, 0x44, 0x2d,
	0xda, 0x52, 0x17, 0xce, 0xca, 0x4b, 0x58, 0x50, 0xdc, 0xa9, 0xa2, 0x16, 0xed, 0x5a, 0x27, 0x98,
	0x2e, 0x96, 0x58, 0x2d, 0xc6, 0x8b, 0x25, 0x96, 0x37, 0x70, 0xd2, 0xfb, 0x9d, 0xe9, 0xb7, 0x6e,
	0x50, 0x55, 0x2d, 0xda, 0xa5, 0xfe, 0xe3, 0x52, 0xc1, 0x2a, 0x20, 0xc6, 0x24, 0xad, 0xb2, 0x34,
	0xd1, 0x94, 0x83, 0x07, 0x56, 0xa7, 0x63, 0x0e, 0x1e, 0xb8, 0x79, 0x80, 0xb3, 0xa9, 0xcb, 0x73,
	0xef, 0x09, 0x67, 0x65, 0xae, 0xa1, 0x8a, 0x68, 0xc8, 0x8f, 0xcf, 0xac, 0xf5, 0x2f, 0x6b, 0xee,
	0xfe, 0x3f, 0xf1, 0x62, 0xd8, 0xcc, 0x7c, 0x12, 0x4a, 0x6b, 0xd8, 0x64, 0xd7, 0x46, 0x67, 0xdc,
	0x3c, 0xc2, 0xd5, 0xe4, 0xf9, 0x08, 0xd6, 0x30, 0x6e, 0xdd, 0x60, 0xfd, 0xfe, 0xd8, 0x00, 0x7b,
	0x37, 0xa8, 0x65, 0x2e, 0x9f, 0x60, 0x57, 0xe5, 0x01, 0xef, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff,
	0x02, 0x03, 0x5c, 0xb1, 0x53, 0x01, 0x00, 0x00,
}
